### ISSUE TITLE
w3c validation

### ISSUE THREAD

**Issue by newschapmj1** [greenido/autocomplete-codelab#1]
I'm not clear if these autocomplete options are supported in commonly used browsers.

**Pros**
 I have this Google example,
http://baymard.com/labs/touch-keyboard-types
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete

**Cons**
CanIuse
http://caniuse.com/#search=autocomplete
not much related information on Stackoverflow
https://validator.w3.org/

**too hard** if you are after a quickish answer

https://html.spec.whatwg.org/multipage/forms.html#autofill

step 8 passed through validator.

```
Error: Bad value cc-name for attribute autocomplete on element input.

From line 14, column 11; to line 15, column 57

          <input name="ccname" id="frmNameCC" required    placeholder="Full Name" autocomplete="cc-name">↩     

Error: Bad value cc-number for attribute autocomplete on element input.

From line 22, column 11; to line 23, column 36

          <input name="cardnumber" id="frmCCNum" required ↩           autocomplete="cc-number">↩     

Error: Bad value cc-csc for attribute autocomplete on element input.

From line 30, column 11; to line 31, column 33

          <input name="cvc" id="frmCCCVC" required ↩           autocomplete="cc-csc">↩     

Error: Bad value cc-exp for attribute autocomplete on element input.

From line 38, column 11; to line 39, column 55

          <input name="cc-exp" id="frmCCExp" required ↩           placeholder="MM-YYYY" autocomplete="cc-exp">↩     
```

**Comment by greenido** [comment]
I hear you :(
As you can see in the link you shared: https://html.spec.whatwg.org/multipage/forms.html#autofill
In the spec all these values are valid (e.g. cc-name etc'). So I wonder why we are getting these errors in the validator.
